baseURL = "https://lcg.ognotes.com"

languageCode = "en-us"
DefaultContentLanguage = "en"
# title = "Linux Certification Guide"
theme = "hugo-theme-techdoc"

hasCJKLanguage = true
metaDataFormat = "yaml"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= true
enableMissingTranslationPlaceholders = true

[languages]
  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'Linux Certification Guide'
    weight = 1
    [languages.en.params]
      subtitle = 'Reference, Tutorials, and Explanations'
      description = 'Working to be Linux most omnibus certification guide'
      
    [languages.en.menus]
[[languages.en.menus.main]]
    name = "Home"
    url = "/en"
    weight = 1
    identifier = 'home'
    pre = "<i class='fa fa-heart'></i>&nbsp;"

[[languages.en.menus.main]]
    name = "X(Twitter)"
    url = "https://x.com/orlando_gentil"
    weight = 2
    identifier = 'twitter'
    # pre = "<b>pre!</b> "
    # post = " <b>post!</b>"
    #[menu.main.params]
    #  class = 'twitter-menu-item'

  [languages.pt]
    contentDir = 'content/pt'
    disabled = false
    languageCode = 'pt-BR'
    languageDirection = 'ltr'
    languageName = 'Brazilian Portuguese'
    title = 'Linux Certification Guide'
    weight = 2
    [languages.pt.params]
      subtitle = 'Referenz, Tutorials und Erklärungen'
      description = "Trabalhando para ser o mais completo guia para certificação Linux"

    [languages.pt.menus]
[[languages.pt.menus.main]]
    name = "Início"
    url = "/pt"
    weight = 1
    identifier = 'home'
    pre = "<i class='fa fa-heart'></i>&nbsp;"

[[languages.pt.menus.main]]
    name = "X(Twitter)"
    url = "https://x.com/orlando_gentil"
    weight = 2
    identifier = 'twitter'
    # pre = "<b>pre!</b> "
    # post = " <b>post!</b>"
    #[menu.main.params]
    #  class = 'twitter-menu-item'


[params]

    # Source Code repository section

    github_repository = "hhttps://github.com/ognotes/LCG"
    version = "0.0.1"

    # Documentation repository section
    # documentation repository (set edit link to documentation repository)
    github_doc_repository = "https://github.com/ognotes/LCG"
    github_doc_repository_path = ""
    github_doc_repository_branch = "master"

    # Analytic section
    google_analytics_id = "" # Your Google Analytics tracking id
    tag_manager_container_id = "" # Your Google Tag Manager container id
    google_site_verification = "" # Your Google Site Verification for Search Console

    # Open Graph and Twitter Cards settings section
    # Open Graph settings for each page are set on the front matter.
    # See https://gohugo.io/templates/internal/#open-graph
    # See https://gohugo.io/templates/internal/#twitter-cards
    title = "Hugo Techdoc Theme"
    images = ["images/og-image.png"] # Open graph images are placed in `static/images`

    # Theme settings section
    # Theme color
    # See color value reference https://developer.mozilla.org/en-US/docs/Web/CSS/color
    custom_font_color = ""
    custom_background_color = ""

    # Documentation Menu section
    # Menu style settings
    menu_style = "slide-menu" # "open-menu" or "slide-menu" or "" blank is as no sidebar

    # Date format
    dateformat = "2024-02-19T13:00:00Z" # default "2 Jan 2006"
    # See the format reference https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference

    # path name excluded from documentation menu
    menu_exclusion = [
        "archives",
        "archive",
        "blog",
        "entry",
        "post",
        "posts",
    ]

    # Algolia site search section
    # See https://www.algolia.com/doc/
    algolia_search_enable = false
    algolia_indexName = "hugo-demo-techdoc"
    algolia_appId = ""
    algolia_apiKey = "" # Search-Only API Key

# Global menu section (moved inside langhuage section)
# See https://gohugo.io/content-management/menus/
#[menu]
#    [[menu.main]]
#        name = "Home"
#        url = "/"
#        weight = 1
#        identifier = 'home'
#        pre = "<i class='fa fa-heart'></i>&nbsp;"

#    [[menu.main]]
#        name = "X(Twitter)"
#        url = "https://x.com/orlando_gentil"
#        weight = 2
#        identifier = 'twitter'
#        # pre = "<b>pre!</b> "
#        # post = " <b>post!</b>"
#        [menu.main.params]
#          class = 'twitter-menu-item'

# Markup configure section
# See https://gohugo.io/getting-started/configuration-markup/
[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.goldmark.renderer]
        unsafe= true
    [markup.tableOfContents]
        startLevel = 2
        endLevel = 6
        ordered = false

[outputs]
    home = ["HTML", "RSS", "Algolia"]

# Algolia Search configure section
[outputFormats.Algolia]
    baseName = "algolia"
    mediaType = "application/json"
    isPlainText = true
    notAlternative = true

[params.algolia]
    vars = [
        "title",
        "summary",
        "content",
        "date",
        "publishdate",
        "description",
        "permalink",
        "keywords",
        "lastmod",
    ]
    params = [
        "tags",
        "categories",
    ]

